# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlanBDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PlanBDemo
pod 'AFNetworking', '~> 3.2.0'
pod 'Masonry', '~> 1.1.0'
pod 'YYCategories', '~> 1.0.4'
pod 'JSONModel', '~> 1.7.0'
pod 'IQKeyboardManager', '~> 5.0.8'
pod 'UICountingLabel', '~> 1.4.1'

end
